BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 15)
BG_BLACK=$(tput setab 0)
BG_RED=$(tput setab 1)
BG_GREEN=$(tput setab 2)
BG_YELLOW=$(tput setab 3)
BG_BLUE=$(tput setab 4)
BG_MAGENTA=$(tput setab 5)
BG_CYAN=$(tput setab 6)
BG_WHITE=$(tput setab 7)
BOLD=$(tput bold)
RESET=$(tput sgr0)

# 256-color extras (usando $'...' para o escape ser expandido corretamente)
LIGHT_PINK=$'\033[38;5;218m'       # rosa claro  (substitui GREEN no menu)
VERY_LIGHT_PINK=$'\033[38;5;225m'  # rosa bem claro (substitui YELLOW no menu)
BG_LIGHT_GRAY=$'\033[48;5;252m'    # fundo cinza claro (substitui BG_BLUE no label)
